### ISSUE TITLE
tp1: the README.md encourages the use of npm, but there is a yarn.lock instead

### ISSUE THREAD

**Issue by mathieu-bour** [gaetanmaisse/ismin-web-2020#1]
In order to freeze the dependencies, wouldn't be better to push a package-losk.json instead generated with npm?

**Comment by gaetanmaisse** [comment]
Ahaha, true! 
I'm a bit uncertain about NPM vs Yarn usage in TPs. Mainly because NPM is shipped with Node so doesn't require an extra install BUT almost every project I'm currently working on (at work and open-source projects) are using Yarn. Plus, I need to confess I do prefer Yarn 🧶 and its vision of the future of JS package managers.

What’s your opinion? Would you go with NPM for simplicity or Yarn that I consider a "better" tool?

**Comment by mathieu-bour** [comment]
I think that Yarn vs Berry vs NPM is an eternal debate. There are a lot of discussions about this topic.
In my honest opinion, there is no need to embarrass the students with this choice since the Yarn features are probably out of the course scope. They will probably "do the work and forget" anyway.
In my company, all our projects runs on the standard NPM in production and we never experienced any issues (apart from degraded performance).

**Comment by gaetanmaisse** [comment]
Fixed with 3544fb95a647e0cf357d8f8aa4a559c20c8f6581.
